
platform :ios, '11.0'

target 'TalkPresidential' do
  use_frameworks!
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'Firebase/AdMob'
end
